### PR TITLE
Fix observers in 2.3.0+

### LINKED ISSUE #481: [Bug] 2.3.1 broke `observes` modifier
### 🐞 Bug description

With the latest version of `ember-concurrency` the _observes_ modifier stopped working.

```js
import Model, { attr } from '@ember-data/model';
import { inject as service } from '@ember/service';
import { task } from 'ember-concurrency';

export default class Parking extends Model {
  @service store;

  @attr('array', { defaultValue: () => [] }) carIds;

  // This tasks should perform everytime `cardIds` changes.
  @task({
    observes: 'carIds.[]',
    drop: true,
  })
  *loadCarsTask() {
    // ...
  }
}
```

```js
import Component from '@glimmer/component';
import { action, set } from '@ember/object';

export default class ParkingBox extends Component {
  @action
  onCarChange(cars) {
    const { parking } = this.args;
    const cardIds = cars.map(({ id }) => parseInt(id));

    set(parking, 'cardIds', cardIds);
  }
}

```
### 😕 Actual Behavior
`loadCarsTask` isn't performing when `carIds` changes.

### 🤔 Expected Behavior
`loadCarsTask` should perform everytime `cardIds` changes.

### 🌍 Environment
- ember-concurrency  `2.3.1`
- ember-source  `4.6.0`
- ember-data `4.2.0`

### PR DESCRIPTION
**Pull request by machty**
Closes #481

It seems #457 removed a call to `_setupEmberKVO`, which was causing observers (and probably some other cases) to stop working.

### CODE REVIEW

File: addon/-private/external/task-decorators.js [hunk 1]
```diff
@@ -23,6 +23,7 @@ function taskFromPropertyDescriptor(
   let tasks = new WeakMap();
   let options = params[0] || {};
   let factory = new factoryClass(key, taskFn, options);
+  factory._setupEmberKVO(target);
```
Comment (maxfierke) [inline addon/-private/external/task-decorators.js:26]: I think the idea was to keep anything ember-specific out of the `external` module, but if we're not doing the separate Ember descriptors, this seems reasonable for now, especially if we're planning on getting rid of observer support. We can also figure out a refactor later if we need to.

**Review by maxfierke — APPROVED** [review]
:octocat: lgtm

File: addon/-private/external/task-decorators.js (hunk 1 above)
Comment (machty) [reply addon/-private/external/task-decorators.js:26]: 👍  Yeah I think we can revisit later

**Comment by esbanarango** [comment]
Thank you @machty and @maxfierke 🙏
